# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-17 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='creator',
        ),
    ]
