# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_blog_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
